### PR TITLE
Change module declaration in "index.d.ts" to "gatsby-plugin-react-intl"

### PR DESCRIPTION
**Pull request by cddlee**
Fixes "Cannot resolve symbol..." error in JetBrains IDEs.

### CODE REVIEW

**Comment by hamidsafdari** [comment]
Hi. Can you please merge this already?

**Comment by Gabsii** [comment]
would be awesome if this could be merged. Otherwise, the package is not really useable with TS 😅

**Comment by KTamas** [comment]
@theowenyoung any update on this? it'd be great to get it merged

**Review by theowenyoung — APPROVED** [review]
Thanks, sorry for the late reply.

**Comment by KTamas** [comment]
@theowenyoung thank you, does this mean you have a new package released in npm soon?

**Comment by theowenyoung** [comment]
Yes, done @3.0.2

**Comment by KTamas** [comment]
thank you!

**Pull request merged**
